# vi: set ft=yaml sw=2 :
---
- name: Append alias to disable Python2 cache
  lineinfile:
      dest: /home/vagrant/.bashrc
      line: "alias python='python -B'"
      owner: vagrant
      regexp: "^alias python='python -B'$"
      state: present
      insertafter: EOF
      create: True

- name: Append alias to disable Python3 cache
  lineinfile:
      dest: /home/vagrant/.bashrc
      line: "alias python3='python3 -B'"
      owner: vagrant
      regexp: "^alias python3='python3 -B'$"
      state: present
      insertafter: EOF
      create: True
