# vi: set ft=yaml sw=2 :
---
- name: Check whether aptitude is installed
  stat:
    path: /usr/bin/aptitude
  register: aptitude_executable

- name: Install aptitude (Ansible apt module dependency)
  raw: apt-get install -y aptitude
  when:
    aptitude_executable.stat.exists == False
